algo:
  feature_extractor:
    learning_rate: 5e-4
    dyn_obs_num: 5
    pretrained_checkpoint_path: "/home/u20/NavRL/isaac-training/training/scripts/ViTLSTM_model.pth"

  actor:
    learning_rate: 5e-4
    clip_ratio: 0.1
    action_limit: 2.0 # m/s

  critic:
    learning_rate: 5e-4
    clip_ratio: 0.1

  entropy_loss_coefficient: 1e-3 # encourage exploration
  training_frame_num: 64
  training_epoch_num: 2
  # num_minibatches: 4 # split into N minibatches
